### ISSUE TITLE
python 3.6

### ISSUE THREAD

**Issue by tom-spalding** [digitalvapor/vondrak#1]
update CI to run on newer python versions.

**Comment by cyschneck** [comment]
Will this fix include Python3.7? 

(currently using Python 3.7.3)
```
$ pip3 install vondrak
Defaulting to user installation because normal site-packages is not writeable
Collecting vondrak
  Using cached vondrak-0.03.tar.gz (9.7 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-orv7dp_6/vondrak_fd5a10937e2e4b92b5877a1ae76855d5/setup.py", line 13, in <module>
          long_description = read('readme.rst'),
        File "/tmp/pip-install-orv7dp_6/vondrak_fd5a10937e2e4b92b5877a1ae76855d5/setup.py", line 7, in read
          return open(os.path.join(os.path.dirname(__file__), *filenames)).read()
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-orv7dp_6/vondrak_fd5a10937e2e4b92b5877a1ae76855d5/readme.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
Thanks!

**Comment by tom-spalding** [comment]
Ah, thanks for the bug report @cyschneck! Will fix this up for 3.7.

**Comment by cyschneck** [comment]
The method that Python3 reads directories has changed, but this should fix it: https://github.com/dreamalligator/vondrak/pull/2

**Comment by tom-spalding** [comment]
Resolved in https://github.com/dreamalligator/vondrak/pull/2.
